### ISSUE TITLE
Deprecation Notices link in documentation sidebar has wrong destination

### ISSUE THREAD

**Issue by stuart-warren** [canonical-web-and-design/snapcraft.io#3038] opened 2020-09-01 20:30 UTC
### Expected behaviour

clicking `deprecation notices` goes to https://snapcraft.io/docs/deprecation-notices

### Steps to reproduce the problem

click `deprecation notices` in sidebar, notice how url is https://snapcraft.io/docs/debug-snaps and pull a confused face

### Specs

- _URL:_ https://snapcraft.io/docs/
- _Operating system:_ MacOS
- _Browser:_ Chrome

**Comment by solazio** [comment] 2020-09-04 08:07
@stuart-warren thank you for reporting this.

The issue is now fixed, and clicking on the `deprecation notices` in the side navigation takes you to https://snapcraft.io/docs/deprecation-notices

**Closed by solazio** 2020-09-04 08:07 UTC
Labels: Priority: High
