### ISSUE TITLE
504 when using store pages

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#3467] opened 2021-03-17 09:42 UTC
### Expected behaviour

Pages perform well.

### Steps to reproduce the problem

Sometimes, I get a 504 error when visiting storefront pages such as https://snapcraft.io/newsflash/settings or https://snapcraft.io/newsflash/releases. Typically this continues for a while, taking ages to respond, then eventually it just "fixes itself" 

I get a blank page with the big Times New Roman 504 error at the top.

Unfortunately I don't see any easy way to debug it. 

### Specs

- _URL:_ https://snapcraft.io/newsflash/settings
- _Operating system:_ Ubuntu 21.04
- _Browser:_ Google Chrome

**Comment by tbille** [comment] 2021-03-17 09:53
@jkfran Theory:
- The error message is sent by nginx,  this means we can't find any logs that could help to debug
- It's possible that we are making an API requests to dashboard, this requests is taking long not timing out
- Gunicorn will timeout after 30 seconds and stop the session
- nginx takes over and throws a 504

I might be wrong, the problem here is that no logs is being recorded and no sentry errors :sweat: 

What do you think?

What we could try:
- request some logs (at least some durations and httpstatus) from store team
- try to deploy the docker image on microk8s and see how could we reproduce this error (slow connection, mock api etc etc)

**Comment by kz6fittycent** [comment] 2021-04-29 15:38
I can confirm @popey's issue. I am getting the same error any time I visit `releases`, `builds`, or `metrics`. 

OS: Pop!_OS 20.10
Browser: Brave

**Comment by jkfran** [comment] 2022-03-08 14:35
Hi! This issue is a duplicate of https://github.com/canonical-web-and-design/snapcraft.io/issues/3585. We dedicated time to it (see https://github.com/canonical-web-and-design/snapcraft.io/issues/3585#issuecomment-1018710897 for all the changes).

I consider this issue to be gone but if you experience this issue again please feel free to reopen. Thank you.

**Closed by jkfran** 2022-03-08 14:35 UTC
Labels: Priority: High, 🚀 Dev ready
