### ISSUE TITLE
Private snap appears as public

### ISSUE THREAD

**Issue by joaomoreno** [canonical-web-and-design/snapcraft.io#1287] opened 2018-11-08 17:55 UTC
### Expected behaviour

Given that my snap is private:

![image](https://user-images.githubusercontent.com/22350/48217461-51f28480-e37f-11e8-9326-d635dde7af42.png)

I expected it to also show `Private` in the snaps overview page:

![image](https://user-images.githubusercontent.com/22350/48217447-4606c280-e37f-11e8-847b-777d905a2ac5.png)

### Specs

- _URL:_ https://snapcraft.io/snaps
- _Operating system:_ macOS
- _Browser:_ Chrome

**Comment by bartaz** [comment] 2018-11-09 08:53
@Lukewh I think we saw this one before? Was it the problem with API reporting different values (listing vs details)?

**Comment by bartaz** [comment] 2018-11-09 10:46
@joaomoreno Thanks for the report. I cannot reproduce the issue on any of my snaps (owned or shared). I see that the store correctly shows `code` as private snap in its snaps details, so it seems that possibly only your account snaps listing may be affected.

Is this snap owned by you, our are you a collaborator? Is this issue still showing up? Does anything change if you try to edit and save anything on the `Listing` page?

**Comment by joaomoreno** [comment] 2018-11-12 07:56
Oh. The issue actually went away when I touched something in the `Listing` page!

Btw, at the Snapcraft Summit last week @sergiusens mentioned this was because the snap was public at creation time and then made private.

Up to you if you wanna close this as fixed.

**Comment by Lukewh** [comment] 2018-11-22 09:54
I believe this is a historic issue. I've just tried multiple times and it seems to work as expected now. Thanks for the report.

**Comment by popey** [comment] 2019-01-07 11:05
We are seeing this again...

![image](https://user-images.githubusercontent.com/1841272/50764884-0e77a200-126c-11e9-98e9-b06493d68021.png)


![image](https://user-images.githubusercontent.com/1841272/50764897-133c5600-126c-11e9-8691-b7a10ccfeb54.png)

**Comment by tbille** [comment] 2019-03-13 11:06
This seems to happen for snaps that has old metadata.

This should be updated in the store api side. Waiting to get a list of snaps from a script wrote by @popey before opening issue on their bugtracker.

**Comment by Lukewh** [comment] 2020-01-16 12:10
Is this still an issue? Do we have any examples? Was the script written? Did the store team implement some kind of fix?

**Comment by danielmutis** [comment] 2020-05-05 15:57
The issue should be fixed. Reopen if needed.

**Closed by danielmutis** 2020-05-05 15:57 UTC
Labels: Priority: High
