### ISSUE TITLE
Can not build snap from specific branch of a GitHub repository

### ISSUE THREAD

**Issue by RetGal** [canonical-web-and-design/snapcraft.io#3790] opened 2021-12-05 19:49 UTC
### Expected behaviour
It builds the new snap from the specified repository/branch.

### Steps to reproduce the problem
Select a repository:
![Bildschirmfoto vom 2021-12-05 20-43-55](https://user-images.githubusercontent.com/19471064/144761259-b3f1508d-8ca5-4663-923a-7199ec8e8c7e.png)
Press enter:
![Bildschirmfoto vom 2021-12-05 20-44-31](https://user-images.githubusercontent.com/19471064/144761267-ec464a56-0495-4db7-b27e-1e19d7253480.png)

### Specs

- [_URL:_](https://snapcraft.io/fensterkitt/builds)
- _Operating system: Debian 11
- _Browser: Firefox ESR

**Comment by jkfran** [comment] 2021-12-06 09:25
Hi @RetGal 

Thank you for opening this issue, this issue is considered a feature request and it is a duplicate of https://github.com/canonical-web-and-design/snapcraft.io/issues/2861

I will close it since we can track the progress with the other one.

**Closed by jkfran** 2021-12-06 09:25 UTC
