### ISSUE TITLE
Build fails in Launchpad while stuck at 'Waiting for builds' at Snapcraft Builds

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [canonical-web-and-design/snapcraft.io#3471] opened 2021-03-20 04:15 UTC
### Expected behaviour

My snap should be built and possibly pushed into
the `latest/edge`.

### Steps to reproduce the problem

1. Check if my `snapcraft.yaml` file is valid with an YAML validator (not sure if there's one of `snapcraft.yaml` file).
2. Connect my repo into my snap for automated builds.
3. Wait for hours for the builds to shown in the Builds tab. Or, dig around Launchpad if it failed.
## Error Log

```
"1 hour ago (Cannot parse snapcraft.yaml from https://github.com/MadeByThePinsHub/dogehouse-electron-app-snap HEAD: unacceptable character #x1f680: special characters are not allowed in "<string>", position 79)  "
```

### Specs

- _Build Logs URL from Launchpad:_ https://launchpad.net/~build.snapcraft.io/+snap/757b5f1030e66126b112a47339b86620
- _Snap Name:_ `dogehouse`
- _Had collaborator access?:_ True
- _Link to snapcraft.yaml`:_ <https://github.com/MadeByThePinsHub/dogehouse-electron-app-snap/blob/master/snap/snapcraft.yaml>

**Comment by AndreiJirohHaliliDev2006** [comment] 2021-03-20 04:17
Here's the evidence

![IMG_20210320_121708](https://user-images.githubusercontent.com/34998342/111858748-431c3380-8976-11eb-8d8b-efbef8547fe9.png)

**Comment by jkfran** [comment] 2021-03-22 12:07
Hi @AndreiJirohHaliliDev2006 ,

I am sure the issue is because of the emoji that you have inside your snapcraft.yaml, it's currently not supported by the Launchpad builders. If you want you can always add it later modifying the description on your snap listing tab.

I am going to close this issue because there is already one issue related to this: https://github.com/canonical-web-and-design/snapcraft.io/issues/3143

PD: To the moon 🚀

**Closed by jkfran** 2021-03-22 12:07 UTC

**Comment by cjwatson** [comment] 2021-03-22 15:35
Thanks for reporting this.  We should have it fixed in Launchpad soon.

**Comment by cjwatson** [comment] 2021-03-25 19:11
This should be fixed now.
