### ISSUE TITLE
Releases page shows incorrect information

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#3141] opened 2020-10-22 08:28 UTC
### Expected behaviour

The signal-desktop snap has only got releases of amd64 builds recently. If I close the edge channel, then leave the screen and come back, some old non-amd64 releases keep appearing in the edge channel. 

### Steps to reproduce the problem

Visit https://snapcraft.io/signal-desktop/releases
Observe many architectures listed in edge channel

![Screenshot from 2020-10-22 09-23-42](https://user-images.githubusercontent.com/1841272/96845586-c0d02780-1448-11eb-8bcc-b0a926d9981c.png)

Close edge channel

![Screenshot from 2020-10-22 09-24-38](https://user-images.githubusercontent.com/1841272/96845613-c75e9f00-1448-11eb-9837-5eef2fc76804.png)

Note no more releases in the edge channel

![Screenshot from 2020-10-22 09-24-47](https://user-images.githubusercontent.com/1841272/96845623-ca598f80-1448-11eb-8075-58c0d92e9eb9.png)

Leave the screen, then come back
Observe the edge channel is populated again

![Screenshot from 2020-10-22 09-25-04](https://user-images.githubusercontent.com/1841272/96845659-d3e2f780-1448-11eb-8c28-f9038f6a935d.png)

WAT

### Specs

- _URL:_ https://snapcraft.io/signal-desktop/releases
- _Operating system:_ Ubuntu Groovy Gorilla
- _Browser:_ Chrome 86

**Comment by jkfran** [comment] 2020-11-23 13:41
Hi @popey ,

I've been playing around with this issue and it seems that is what we get from the API when these conditions are met. I can reproduce exactly the same issue using the snapcraft CLI:

```
$ snapcraft close testfran8 edge
Track    Arch    Channel    Version    Revision
latest   amd64   stable     -          -
                 candidate  -          -
                 beta       -          -
                 edge       0.1        14
         arm64   stable     -          -
                 candidate  -          -
                 beta       0.1        15
                 edge       ↑          ↑
         i386    stable     -          -
                 candidate  -          -
                 beta       -          -
                 edge       0.1        13

The edge channel is now closed.
```

And then I am able to install the snap:
```
$ snap install --edge testfran8 
testfran8 (edge) 0.1 from Francisco Jiménez Cabrera (jkfran) installed
```

Looks like currently, it doesn't close the channel if there are architectures that don't have a release in the next channel. This should be reported to the snap store team.

**Comment by jkfran** [comment] 2020-11-23 13:50
@popey I am going to close the issue, I created a ticket on Launchpad:
https://bugs.launchpad.net/snapcraft/+bug/1905278

Thank you!

**Closed by jkfran** 2020-11-23 13:50 UTC
Labels: Being investigated, Priority: Medium

**Comment by popey** [comment] 2020-11-23 14:15
Thanks!
