### ISSUE TITLE
France...

### ISSUE THREAD

**Issue by therealjuan** [canonical-web-and-design/snapcraft.io#2003] opened 2019-06-13 18:54 UTC
![image](https://user-images.githubusercontent.com/8167677/59459564-0f989680-8deb-11e9-9e25-e9a6560aa2da.png)

...I could provide more details about this issue but just leaving it empty for now for the LOLz during standup.

**Comment by bartaz** [comment] 2019-06-14 06:47
I guess we should assign @tbille to this ;)

**Comment by bartaz** [comment] 2019-06-14 06:52
Joking aside, not sure if it's an issue with `pycountry` that provides the names or with out map topojson that simply treats "French Guiana" as a territory of "France".

**Comment by tbille** [comment] 2019-06-14 08:17
@bartaz 	@therealjuan 	this is a issue that has been there for a long time. We need to update the map to have one that respects full the ISO3166. It's not a bug from the API.

**Comment by bartaz** [comment] 2019-06-14 08:21
Yes, it seems to be the map that has France and Guiana as one territory. There is another, more detailed topojson, but it also is significantly larger and contains a lot of border details that we don't need. It will make loading the map slower and the map SVG itself will be larger because of the details as well. (And in not sure if it has France and Guiana separate, that's something to verify).

**Comment by bartaz** [comment] 2019-06-14 12:36
https://www.youtube.com/watch?v=WLMw9SPcFBI

**Comment by bartaz** [comment] 2019-06-14 12:50
I checked, and unfortunately the topojson/world-atlas map data that we use doesn't have separate entity for Guiana (even in latest version of the data or in larger scale).

**Comment by Lukewh** [comment] 2020-05-07 08:40
Nearly a year on, we should review this.

**Comment by tbille** [comment] 2020-05-07 08:43
The world-map still needs to be updated to get the proper ISO format.

**Comment by solazio** [comment] 2020-09-02 15:51
As French Guyana [is still part of France](https://en.wikipedia.org/wiki/2010_French_Guianan_status_referendum) and even though it has a separate country code in [ISO 3166](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes), that code is a sub-division code. 

The newer version of [topojson](https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json) I found is 100kB bigger, therefore I will not update it.

Therefore I will close this issue until French Guyana people will vote yes for their independence.

**Comment by tbille** [comment] 2020-09-09 08:03
I am reopening this issue.

The reason why it is slitted in the ISO 3166 is because some users could do some more "continental analysis" instead of a country based one.

> The newer version of topojson I found is 100kB bigger, therefore I will not update it.

I just see 6k difference between the maps I don't think this is an issue.

```
$ ls -l
total 208K
-rw-rw-r-- 1 toto toto 100K Sep  8 20:52 current-map.json
-rw-rw-r-- 1 toto toto 106K Sep  8 21:00 new-map.json
```

**Comment by solazio** [comment] 2020-09-09 10:26
Comparing the existing json to the [new one](https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json) on my machine it shows that the new one is double in size.
```
js|master⚡ ⇒ ls -l
total 328
drwxrwxr-x 2 ovidiu docker   4096 Aug 25 09:27 base
drwxrwxr-x 2 ovidiu docker   4096 Aug 25 09:27 config
drwxrwxr-x 2 ovidiu docker   4096 Aug 10 13:34 dist
drwxrwxr-x 2 ovidiu docker   4096 Aug 25 09:27 libs
drwxrwxr-x 2 ovidiu ovidiu   4096 Sep  8 13:26 modules
drwxrwxr-x 4 ovidiu docker   4096 Sep  7 18:37 public
drwxrwxr-x 8 ovidiu docker   4096 Aug 25 09:27 publisher
-rw-rw-r-- 1 ovidiu ovidiu 102116 Sep  9 11:19 world-110m.v1.json
-rw-rw-r-- 1 ovidiu ovidiu 202398 Sep  9 11:20 world-110m.v1-new.json
```

Also, the [new one](https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json) does not have French Guyana so I see no point using it.

Are you sure you were not looking at a different topojson?

**Comment by jkfran** [comment] 2021-11-02 12:04
I am going to close the issue. The library maintainers consider this to be correct:
https://github.com/topojson/world-atlas/issues/33

**Closed by jkfran** 2021-11-02 12:04 UTC
Labels: Priority: High, Good first issue 🔰, Hacktoberfest
