### ISSUE TITLE
Releases heading not shown on narrow screen

### ISSUE THREAD

**Issue by stuartlangridge** [canonical-web-and-design/snapcraft.io#1979] opened 2019-06-08 14:17 UTC
### Expected behaviour
The releases tab in the snap store admin is available on my phone.
### Steps to reproduce the problem
View the admin on a narrow screen.
### Specs

- _URL:_ https://snapcraft.io/snaps
- _Operating system:_ Android
- _Browser:_ brave or Chrome

**Comment by bartaz** [comment] 2019-06-10 08:56
Thanks for the report. We are aware of the lack of mobile support on publisher pages in snapcraft.io.
We hope to get this work scheduled.

Closing this for now, as it's duplicate of #1352.

**Closed by bartaz** 2019-06-10 08:56 UTC
