### ISSUE TITLE
Permission "package_release" is required as a macaroon caveat.

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#1387] opened 2018-11-30 14:25 UTC
I was trying to release a package and got a strange error. I selected the funky upside-down enter button on the left next to the edge channel and then apply.

"Error:Error while releasing 1.3.0 (67) to latest/beta, latest/stable. Permission "package_release" is required as a macaroon caveat."

![image](https://user-images.githubusercontent.com/1841272/49294718-aa630080-f4ab-11e8-8b3b-d96fc312026b.png)

**Comment by tbille** [comment] 2018-11-30 15:32
@popey could you try to logout and login again and try again the process?

**Comment by tbille** [comment] 2018-12-10 17:05
This error must have been openned during the transition with the new way we use macaroons now. I am closing this issue since no one mentionned it since.

The error is an API error, the issue should be open on snapstore side for other cases where the API could fail.

**Comment by popey** [comment] 2019-02-04 14:24
I just had it again.

![screenshot from 2019-02-04 14-23-01](https://user-images.githubusercontent.com/1841272/52213994-8693b080-2888-11e9-963f-ae56e2ef3d79.png)

**Comment by popey** [comment] 2019-02-18 14:41
Still happening...  <3 
![screenshot_20190218_144116](https://user-images.githubusercontent.com/1841272/52958115-515c8780-338b-11e9-969f-747232f37a47.png)

**Comment by tbille** [comment] 2019-03-13 10:59
### From discussion with @popey 

It seems bug comes when having the browser with this page open for more than 24 hours.

### Problem to investigate

Here the problem comes from the fact that the macaroon needs to be refreshed.

**Particularity of this endpoint** When releasing we call an [api endpoint](https://github.com/canonical-websites/snapcraft.io/blob/master/webapp/publisher/snaps/views.py#L618) instead of a view. We would need to investigate if when the response comes back if it updates the session (?).

**To to reproduce:** leave browser on the release page for more than 24 hours (lol) or modify locally the way we request macaroons to get one that expires faster than 24 hours (adding the parameter [expires](https://dashboard.snapcraft.io/docs/api/macaroon.html#request-a-macaroon) when requesting the macaroon)

**Comment by tbille** [comment] 2020-08-18 16:31
Issue not seen in a while. Closing for now.

**Closed by tbille** 2020-08-18 16:31 UTC
Labels: Priority: Medium
