### ISSUE TITLE
rhel instructions for installing duplicity are missing a step

### ISSUE THREAD

**Issue by ralmond** [canonical-web-and-design/snapcraft.io#3403] opened 2021-02-06 20:53 UTC
### Expected behaviour
Expected following the instructions would install duplicity on my machine.

### Steps to reproduce the problem
Follow steps on web page on a machine in which snapd was not previously installed.
Steps work up until point where it calls for
    sudo snap install duplicity --classic
which fails with the error message:
    error: too early for operation, device not yet seeded or device model not acknowledged

### Specs

A little bit of digging indicated that a step was missing.  I needed to run
    systemctl restart snapd.seeded.service

Then `snap` behaved as expected.

- _URL:_  https://snapcraft.io/install/duplicity/rhel
- _Operating system:_  RHEL 7.8
- _Browser:_  NA

**Comment by jkfran** [comment] 2021-11-04 09:48
Duplicate of https://github.com/canonical-web-and-design/snapcraft.io/issues/3403 but for a different snap.

**Closed by jkfran** 2021-11-04 09:48 UTC
Labels: Priority: High
