### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by messey-bilal** [canonical-web-and-design/snapcraft.io#3856] opened 2022-01-18 14:33 UTC
### Expected behaviour
the build of snap
### Steps to reproduce the problem
i put my username and the link of git repo which is below but i receive an error message (internal server error)
### Specs

- _URL:_https://github.com/messey-bilal/downloadaccelerator
- _Operating system:_debian
- _Browser:_firefox

**Comment by jkfran** [comment] 2022-01-26 14:21
Hello @messey-bilal ,

I can see that the snap is currently connected to your repo. I am going to close this issue as it was probably caused by some downtime on snapcraft.io. Please always check status.snapcraft.io.

**Closed by jkfran** 2022-01-26 14:21 UTC
