### ISSUE TITLE
Can not set application to private from settings 

### ISSUE THREAD

**Issue by keshavbhatt** [canonical-web-and-design/snapcraft.io#2951] opened 2020-07-13 19:00 UTC
### Expected behavior
Ability to set the published application to private from the settings section.
### Steps to reproduce the problem

1. Go to settings of any application published to snap store,
try to set its listing to private. 
2. On clicking save button getting the error :
"The 'description' field cannot contain control or private unicode characters."
### Specs

- _URL:_ https://snapcraft.io/[app]/settings
- _Operating system:_ Ubuntu 16.04 LTS
- _Browser:_ Google Chrome Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by jkfran** [comment] 2020-07-14 09:19
It seems to be related with https://github.com/canonical-web-and-design/snapcraft.io/issues/1360

Investigating :mag:

**Comment by jkfran** [comment] 2020-07-14 10:19
Hello @keshavbhatt ,

Could you tell us the snap name? Also, did you add the snap description manually or with the snapcraft.yaml? Did this error appears if you change any other information in the listing tab or is only when you try to make the snap private?

**Comment by keshavbhatt** [comment] 2020-07-14 12:24
I had some old snap apps in my account which i later made private from the alternate website. I don't remember if i set description manually or it picked from snapcraft yaml file.

**Comment by jkfran** [comment] 2020-07-15 10:24
Could be related as well with https://github.com/canonical-web-and-design/snapcraft.io/issues/356

I tried to reproduce this issue, using `\r\n` for new lines in the snapcraft.yaml and then make the snap private without any luck. I tried this because we are replacing `\r\n` to `\n` but only for the POST request in the listing form:
https://github.com/canonical-web-and-design/snapcraft.io/blob/1f7ee8fc19ef85498abc417b494ec475aece7b56/webapp/publisher/snaps/listing_views.py#L207-L209

I am going to close the issue because we can't reproduce it, it would be nice to have the description value and the snap that is failing next time.

Thank you!

**Closed by jkfran** 2020-07-15 10:24 UTC
Labels: Priority: Medium
