### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by apdw3** [canonical-web-and-design/snapcraft.io#2914] opened 2020-06-25 15:09 UTC
Attempting to create my Listing Details on the Snapcraft site repeatedly results in a "413 Request Entity Too Large" error.

Attempting to preview the page results in a Internal server error.

**Comment by Lukewh** [comment] 2020-06-29 08:25
Duplicate of https://github.com/canonical-web-and-design/snapcraft.io/issues/2503

**Closed by Lukewh** 2020-06-29 08:25 UTC
