### ISSUE TITLE
No option to dispute reserved names

### ISSUE THREAD

**Issue by therealjuan** [canonical-web-and-design/snapcraft.io#1987] opened 2019-06-11 14:16 UTC
### Steps to reproduce
1. Log in into your account
2. Go to [Register a snap name ](https://snapcraft.io/register-snap)
3. Enter a reserved name like `cmake`

### What is happening?
You get the message: `The snap name "cmake" is reserved.` with no option to file a dispute. Please note that we currently offer the option to file a dispute if the name already exists on the store so we should give an option to the publisher to use the `file a dispute` interface.

### What should happen?
The publisher should be able to make a claim on the reserved name and view the following message:
`The new message could be `The snap name "cmake" is reserved. You can file a dispute to request a transfer of ownership or register a new name below.`
Then it could be redirected to the [file a dispute interface](https://snapcraft.io/register-name-dispute?snap-name=cmake).

**Comment by evandandrea** [comment] 2019-06-11 14:20
Dupe of #1885.

**Closed** 2019-06-11 14:26 UTC
