### ISSUE TITLE
https://snapcraft.io/build: support building snaps from more than the default branch

### ISSUE THREAD

**Issue by kyrofa** [canonical-web-and-design/snapcraft.io#2774] opened 2020-05-20 17:05 UTC
Last I checked, https://snapcraft.io/build only supported building snaps from the default branch. Is that still the case? What about tags?

First of all, only supporting the default branch assumes a particular workflow that not all projects use. For example, gitflow doesn't use the default branch as a development trunk at all. This also doesn't support the _very_ common use-case of release branches (a 3.0 branch that has 3.0.1, 3.0.2, etc).

@Lukewh asked me to specify what I'd _like_ to see. In an ideal world, I'd like to be able to specify a relationship between the git branch and the snap track. For example, the Nextcloud snap has `11`, `12`, `13`, `14`, `15`, `16`, `17`, and `master` branches. Whenever I land a commit to `master` I get a snap on `latest/edge`. Whenever I land a commit on `17`, I get a snap on `17/edge`, and so on. The only way I can do this today is to setup a sync from github to launchpad and then use launchpad to build a snap on changes to a given branch. This type of workflow is super common for larger projects, but getting that setup in Launchpad is non-trivial. It'd be great if https://snapcraft.io/build supported it with a decent UI.

That would be a great story, but I realize there's quite a bit of work outlined there. Is there a shorter-term thing we can do to enable projects using release branches like that without making them build snaps themselves or manually setup builds in LP? For example, regarding my above question: if we build on tag pushes we have somewhat of a workaround, it's just not entirely clear if that's supported.

**Comment by jkfran** [comment] 2021-11-03 16:36
Duplicate of https://github.com/canonical-web-and-design/snapcraft.io/issues/2861

**Closed by jkfran** 2021-11-03 16:36 UTC
Labels: Priority: Medium, Feature 🎁
