### ISSUE TITLE
js RangeError when listing branches on snapcraft.io releases page

### ISSUE THREAD

**Issue by k15tfu** [canonical-web-and-design/snapcraft.io#3021] opened 2020-08-21 13:22 UTC
Hi.

When I click on `p-releases-table__branches` item to see current branches for some channel on https://snapcraft.io/XXX/releases page the whole `release-history` div disappears, and I see the following error in Chrome developer console:
```
5raven.min.js?v=daf037c:2 RangeError: Invalid time value
    at p (index.js:134)
    at Zr (index.js:111)
    at ia (channelHeading.js:300)
    at Gi (react-dom.production.min.js:153)
    at gl (react-dom.production.min.js:261)
    at cu (react-dom.production.min.js:246)
    at lu (react-dom.production.min.js:246)
    at Zl (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Ba (react-dom.production.min.js:122)
    at $a (react-dom.production.min.js:123)
    at Wa (react-dom.production.min.js:122)
    at A (react-dom.production.min.js:287)
    at Qt (react-dom.production.min.js:68)
    at HTMLDocument.d (raven.min.js?v=daf037c:2)
```

Originally reported here: https://forum.snapcraft.io/t/js-rangeerror-when-listing-branches-on-snapcraft-io-releases-page/19433

### Expected behaviour
List of branches should be listed.

### Steps to reproduce the problem
Click on `p-releases-table__branches` item.

### Specs

- _URL:_ https://snapcraft.io/XXX/releases
- _Operating system:_ Windows 10
- _Browser:_ Chrome

**Comment by jkfran** [comment] 2020-08-24 09:53
This is duplicate of https://github.com/canonical-web-and-design/snapcraft.io/issues/3010, we have released a fix for it, it should be working in production in a few minutes. Thank you!

**Closed by jkfran** 2020-08-24 09:53 UTC
Labels: Priority: High
